### ISSUE TITLE
CSS does not highlight nested `var()`

### ISSUE THREAD

**Issue by miragecraft** [scrivo/highlight.php#106]
With nested var() assignment, meaning using custom property as fallback for other custom properties, the nested `var` is not highlighted as it should.

Example:
```css
* {
 background: var(--red, var(--blue, green));
}
```

Only the first `var` is highlighted.
