### ISSUE TITLE
is line numbers supported?

### ISSUE THREAD

**Issue by OoqwqoO** [scrivo/highlight.php#19]

**Comment by allejo** [comment]
Nope.

This project is a direct and loyal port of the JS project. Since the [JS project doesn’t support line numbers by choice](http://highlightjs.readthedocs.io/en/latest/line-numbers.html), this project doesn’t support them as well.

Line numbers would have to be accomplished by manually with your own code or a separate project.

**Comment by OoqwqoO** [comment]
OK, I will try it

**Comment by paxperscientiam** [comment]
@qwqoffice I managed to add line numbers in the following way.

Wrap each line of code in `<span class='enumerate'></span>` and then apply the following style.

```CSS
pre.hljs:before {
  counter-reset: listing;
}

pre.hljs span.enumerate {
  counter-increment: listing;
}

pre.hljs span.enumerate::before {
  content: counter(listing) "  ";
  display: inline-block;
}
```

Good luck.
